services:
  - type: cron
    name: ai-radar-bot
    schedule: "0 4 * * *"
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: your_token_here
      - key: CHAT_ID
        value: your_chat_id_here
